SUPER_CONFIG_PATH: /data/users/litianhao/hsmot_code/MOTIP/configs/197_base.yaml

OUTPUTS_DIR: /data/users/litianhao/hsmot_code/workdir/motip/pretrain_10lrfconv_distill_exp2

SAMPLE_LENGTHS: [1]       # Only sampling one frame for detection

DETR_NUM_TRAIN_FRAMES: 100                                # >> BS

# # Train Setting:
TRAIN_STAGE: only_detr
EPOCHS: 40
LR: 2.0e-4
LR_WARMUP_EPOCHS: 0
SCHEDULER_MILESTONES: [25]
SCHEDULER_GAMMA: 0.1
BATCH_SIZE: 4
ACCUMULATE_STEPS: 1

#首层10倍(相对于backbone)
LR_DICTIONARY_NAMES: [backbone.0.body.conv1.weight]
LR_DICTIONARY_SCALE: 1

DETR_PRETRAIN: /data/users/litianhao/hsmot_code/workdir/distill/hintlayer:2_3_4_hintweights:1_1_1_firstconvLrScale:10_lr:1e-06_1/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint_8ch_interpolate_distill.pth

NUM_WORKERS: 2

# # Eval:
INFERENCE_ONLY_DETR: True
SAVE_CHECKPOINT_PER_EPOCH: 5

SAVE_DEBUG_DIR: /data/users/litianhao/hsmot_code/workdir/motip/pretrain_10lrfconv_distill_exp2/debug
SAVE_DEBUG_IMG_INTERVAL: 100