SUPER_CONFIG_PATH: /data/users/wangying01/lth/hsmot/MOTIP/configs/99_joint.yaml

OUTPUTS_DIR: /data/users/wangying01/lth/hsmot/workdir/motip_99/pretrain_10lrfconv_noItPretrain_joint

# Training Scheduler:
EPOCHS: 14
LR: 1.0e-4
LR_BACKBONE_NAMES: [backbone.0]
LR_BACKBONE_SCALE: 0.1
LR_LINEAR_PROJ_NAMES: [reference_points, sampling_offsets]
LR_LINEAR_PROJ_SCALE: 0.05
LR_WARMUP_EPOCHS: 1
WEIGHT_DECAY: 0.0005
CLIP_MAX_NORM: 0.1
SCHEDULER_TYPE: MultiStep
SCHEDULER_MILESTONES: [8, 12]

#首层10倍(相对于backbone)
LR_DICTIONARY_NAMES: [backbone.0.body.conv1.weight]
LR_DICTIONARY_SCALE: 1

RESUME_MODEL:
INFERENCE_ONLY_DETR: False
DETR_PRETRAIN: /data/users/wangying01/lth/hsmot/workdir/motip/pretrain_10lrfconv_noItPretrain/checkpoint_119.pth

# RESUME
RESUME_MODEL: /data3/litianhao/hsmot/motip_99/pretrain_10lrfconv_noItPretrain_joint/checkpoint_2.pth