SUPER_CONFIG_PATH: ./configs/autodl_pretrain_hsmot8ch.yaml

SAMPLE_LENGTHS: [1]       # Only sampling one frame for detection

DETR_NUM_TRAIN_FRAMES: 100                                # >> BS

# # Train Setting:
TRAIN_STAGE: only_detr
EPOCHS: 20
LR: 2.0e-4
LR_WARMUP_EPOCHS: 0
SCHEDULER_MILESTONES: [15]
SCHEDULER_GAMMA: 0.1
BATCH_SIZE: 4
ACCUMULATE_STEPS: 1

#首层10倍(相对于backbone)
LR_DICTIONARY_NAMES: [backbone.0.body.conv1.weight]
LR_DICTIONARY_SCALE: 1


# # Eval:
INFERENCE_ONLY_DETR: True
SAVE_CHECKPOINT_PER_EPOCH: 4

OUTPUTS_DIR: /root/hsmot/workdir/motip/pretrain_10lrconv_LoadPretrainRight
